print("      _      ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("     __      ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("    ___      ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("   ____      ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("  _____      ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("  _____      ")
print("             ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("   ____      ")
print("             ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("    ___      ")
print("             ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("     __      ")
print("             ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("      _      ")
print("             ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")
print("      _      ")
print("      ^      ")
print("     /#\     ")
print("    /###\    ")
print("   /     \   ")
print("  /       \  ")
print(" / ^-^-^-^ \ ")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|  |     |  |")
print("|||||||||||||")
print("|||||||||||||")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@")
print(" @@@@@@@@@@@ ")